### PR TITLE
Updated fastlane recommendation

### PR DESCRIPTION
**Pull request by KrauseFx**
Due to the [inactivity](https://github.com/nomad/shenzhen/commits/master) of [shenzhen](https://github.com/nomad/shenzhen/commits/master) and open issues around the latest iTunes Connect changes it's recommended to use [fastlane](https://fastlane.tools) with [gym](https://github.com/fastlane/gym).

### CODE REVIEW

**Comment by ngs** [comment]
+1

**Comment by rishimkumar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;YXhkJ7pc&#x2F;340-look-at-felix-s-outer-pr"> Look at Felix&#39;s outer PR</a>

**Comment by KrauseFx** [comment]
What's happening here :cry:

**Comment by appplemac** [comment]
@KrauseFx No worries, I’ll take care of it. Thanks for pushing the change.

**Comment by KrauseFx** [comment]
Should I close my 2 pull requests?

**Comment by appplemac** [comment]
@KrauseFx I’ll update them once the change is merged and will close them myself. Cheers!

**Comment by appplemac** [comment]
Addressed in https://github.com/circleci/frontend/commit/ca2ba6781f63af7d5ec2250c04b3895493efc4e1.

**Pull request closed without merging**
