### PR TITLE
Updated background-process YAML syntax.

### PR DESCRIPTION
**Pull request by Bekt**
Doesn't build otherwise. :+1:

### CODE REVIEW

**Comment by marcomorain** [comment]
Thanks @Bekt !

**Comment by marcomorain** [comment]
I've applied this patch to our internal private fork here: https://github.com/circleci/frontend-private/commit/44a2f65a297c2e46956e787d886830c277fe6584

This will merge forward into this repo when our build runs.

Thanks again @Bekt

**Comment by marcomorain** [comment]
That's merged here: https://github.com/circleci/frontend/commit/44a2f65a297c2e46956e787d886830c277fe6584

**Comment by Bekt** [comment]
:100:

**Pull request closed without merging**
